### ISSUE TITLE
Some stations have invalid A_0 coefficients

### ISSUE THREAD

**Issue by jaybo** [pauls-3d-things/tide-estimation#1]
This isn't really a bug in your code,  but I don't know how else to surface the issue.
Some stations such as the following have unexpectedly huge `A_0` coefficients:
```
# Search result for buoy Id = 25
# ID=25
# name=450 NM Northeast of Tokyo, Japan
# latitude=38.7062492370605
# longitude=148.664993286133
# mult x=1
# mult y=1
# offset x=0
# offset y=0
# MovAvg=-1
# Harmonics=HARMONICS_WE:0,5696.34578987306,0...
```
Where the `5696.34578987306` value gives an enormous resulting tide value. (Most stations have an A_0 value plus or minus a few meters).
Are these instances where the `Continuous Harmonics Determination method` has failed to converge, or what?  Do you know any way of filtering out the bad/invalid stations?

Thanks, Jay

**Comment by jaybo** [comment]
Accidentally closed...

**Comment by uvwxy** [comment]
Wohooo I never thought this repo would get any attention ever 😁 . So thanks for the issue 👍 .

I looked at the station you mentioned, and the tide data displayed is drawn in the 5k range:
<img width="800" alt="Screenshot 2019-07-18 at 20 22 25" src="https://user-images.githubusercontent.com/930238/61482052-07a7b580-a99a-11e9-86c8-552a9aea01e2.png">

Looking at this link: [https://www.ndbc.noaa.gov/station_page.php?station=21418](https://www.ndbc.noaa.gov/station_page.php?station=21418), the depth at that spot is given with: 5772m.

And they have a similar chart:

<img width="417" alt="Screenshot 2019-07-18 at 20 32 47" src="https://user-images.githubusercontent.com/930238/61482571-3eca9680-a99b-11e9-82c5-45e73659489c.png">
    
So, I assume the coefficents are correct and the reported values are actual water depth values. The outliers are just in places that are a bit deeper than most reported locations.

**Comment by uvwxy** [comment]
If you look at the resulting tide (= Math.abs(dailyMax - dailyMin)) is not that big. Just the values themselves :)

**Comment by jaybo** [comment]
Great, thanks for explaining this issue!
BTW, did you ever figure out the origin of the one day time offset for t0 (1899-12-30 vs 1900-01-01)?

**Comment by uvwxy** [comment]
No, this is still a mystery to me.
